name: Lint and Catalog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Lint workflows
      run: python3 scripts/lint_workflows.py

    - name: Catalog workflows
      run: python3 scripts/catalog_workflows.py

    - name: Commit and push if catalog changed
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add docs/catalog.json docs/catalog.md
        git diff --staged --quiet || (git commit -m 'Update workflow catalog' && git push)
